// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHadl9GxaHroedD9zG2BFeCl6cHlYM8HU',
    appId: '1:173444476399:web:31d5d452298b6048989a1a',
    messagingSenderId: '173444476399',
    projectId: 'tripfinity-466014',
    authDomain: 'tripfinity-466014.firebaseapp.com',
    storageBucket: 'tripfinity-466014.firebasestorage.app',
    measurementId: 'G-NR1Z2RRD5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtWXYSZbPy-6ffPZY0JO55XQC_WDdSw3M',
    appId: '1:173444476399:android:7dce88bfe1c7c3cd989a1a',
    messagingSenderId: '173444476399',
    projectId: 'tripfinity-466014',
    storageBucket: 'tripfinity-466014.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Q9nBTiU5CG1MDaEdpm_MjtbBo4IIj24',
    appId: '1:173444476399:ios:1b9fc1167f5e6d89989a1a',
    messagingSenderId: '173444476399',
    projectId: 'tripfinity-466014',
    storageBucket: 'tripfinity-466014.firebasestorage.app',
    androidClientId:
        '173444476399-5l4828tlfd9jq2v3j1gjirl9f3gks5ej.apps.googleusercontent.com',
    iosClientId:
        '173444476399-jbcv4644evd91i21eou9db5l92a139ei.apps.googleusercontent.com',
    iosBundleId: 'com.vn.tripfinity.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Q9nBTiU5CG1MDaEdpm_MjtbBo4IIj24',
    appId: '1:173444476399:ios:1b9fc1167f5e6d89989a1a',
    messagingSenderId: '173444476399',
    projectId: 'tripfinity-466014',
    storageBucket: 'tripfinity-466014.firebasestorage.app',
    androidClientId:
        '173444476399-5l4828tlfd9jq2v3j1gjirl9f3gks5ej.apps.googleusercontent.com',
    iosClientId:
        '173444476399-jbcv4644evd91i21eou9db5l92a139ei.apps.googleusercontent.com',
    iosBundleId: 'com.vn.tripfinity.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHadl9GxaHroedD9zG2BFeCl6cHlYM8HU',
    appId: '1:173444476399:web:811bbdffa3f40495989a1a',
    messagingSenderId: '173444476399',
    projectId: 'tripfinity-466014',
    authDomain: 'tripfinity-466014.firebaseapp.com',
    storageBucket: 'tripfinity-466014.firebasestorage.app',
    measurementId: 'G-K1W1SFVC04',
  );
}
