# -*- coding: utf-8 -*-
"""general_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROxLb7xNYHt12WDGA2sqPoeQmLpr-nF7
"""

import pandas as pd
import numpy as np
import os
from google.colab import drive

# ============================================
# BƯỚC 1: KẾT NỐI DRIVE & LOAD DATA
# ============================================
drive.mount('/content/drive')
BASE_PATH = "/content/drive/MyDrive/tripfinity/data"

INPUT_ITEM_FILE = "ai_item_tower_export_20251217_181044.csv"
OUTPUT_FILE = "generated_user_item_interactions_50k_realistic.csv"

input_path = os.path.join(BASE_PATH, INPUT_ITEM_FILE)
output_path = os.path.join(BASE_PATH, OUTPUT_FILE)

if os.path.exists(input_path):
    print("✅ Đã tìm thấy file Item. Đang xử lý...")
    items = pd.read_csv(input_path)

    # Xử lý giá tiền (fill missing và ép kiểu số)
    items['price'] = pd.to_numeric(items['price'], errors='coerce').fillna(items['price'].median())

    # Lấy danh sách index của các nhóm item theo quy luật
    # 1. Nhóm Rẻ: Giá dưới 500k
    cheap_items = items[items['price'] < 500000].index.tolist()

    # 2. Nhóm Sang: Giá trên 2 triệu VÀ là Hotel
    luxury_items = items[(items['price'] > 2000000) & (items['item_type'] == 'hotel')].index.tolist()
    # Fallback: Nếu ít item sang quá thì lấy giá > 1tr
    if len(luxury_items) < 10:
        luxury_items = items[items['price'] > 1000000].index.tolist()

    # 3. Nhóm Tour: Chỉ lấy Tour
    tour_items = items[items['item_type'] == 'tour'].index.tolist()

    print(f"📊 Thống kê nguồn dữ liệu:")
    print(f"   - Số lượng Item Rẻ: {len(cheap_items)}")
    print(f"   - Số lượng Item Sang: {len(luxury_items)}")
    print(f"   - Số lượng Item Tour: {len(tour_items)}")

    # ============================================
    # BƯỚC 2: SINH DỮ LIỆU CÓ QUY LUẬT (PATTERN)
    # ============================================
    TOTAL_INTERACTIONS = 50000
    user_min = 3
    user_max = 2500

    # Chia User thành 3 nhóm sở thích (Mỗi nhóm chiếm 1/3 lượng user ID)
    user_ids_all = np.arange(user_min, user_max + 1)
    np.random.shuffle(user_ids_all)

    # Chia nhóm user ID
    split_1 = len(user_ids_all) // 3
    split_2 = split_1 * 2

    users_budget = user_ids_all[:split_1]       # Nhóm thích rẻ
    users_luxury = user_ids_all[split_1:split_2] # Nhóm thích sang
    users_tour   = user_ids_all[split_2:]        # Nhóm thích tour

    generated_rows = []

    # Hàm sinh random action weight
    # Logic: Nếu đúng sở thích thì thường action sẽ mạnh (booking/favorite)
    actions_map = ['view', 'click', 'search', 'favorite', 'book']
    weights_map = [2, 3, 1, 4, 5]
    probs_high_intent = [0.1, 0.2, 0.1, 0.3, 0.3] # Nhóm thích -> Tỉ lệ book cao
    probs_low_intent  = [0.5, 0.3, 0.1, 0.05, 0.05] # Nhóm xem chơi

    print("🔄 Đang sinh dữ liệu tương tác theo kịch bản...")

    # --- KỊCH BẢN 1: NHÓM BÌNH DÂN (BUDGET) ---
    # Sinh 20k dòng cho nhóm này
    for _ in range(20000):
        u_id = np.random.choice(users_budget)
        # BẮT BUỘC chọn item rẻ -> Model sẽ học được: User này associated với Price thấp
        i_idx = np.random.choice(cheap_items)

        # Chọn action
        act_idx = np.random.choice(len(actions_map), p=probs_high_intent)

        item_row = items.iloc[i_idx]
        generated_rows.append([u_id, item_row['item_id'], item_row['item_type'],
                               actions_map[act_idx], weights_map[act_idx]])

    # --- KỊCH BẢN 2: NHÓM SANG TRỌNG (LUXURY) ---
    # Sinh 15k dòng
    for _ in range(15000):
        u_id = np.random.choice(users_luxury)
        # BẮT BUỘC chọn item đắt
        i_idx = np.random.choice(luxury_items)

        act_idx = np.random.choice(len(actions_map), p=probs_high_intent)

        item_row = items.iloc[i_idx]
        generated_rows.append([u_id, item_row['item_id'], item_row['item_type'],
                               actions_map[act_idx], weights_map[act_idx]])

    # --- KỊCH BẢN 3: NHÓM YÊU TOUR (TOUR LOVERS) ---
    # Sinh 15k dòng còn lại
    for _ in range(15000):
        u_id = np.random.choice(users_tour)
        # BẮT BUỘC chọn tour
        i_idx = np.random.choice(tour_items)

        act_idx = np.random.choice(len(actions_map), p=probs_high_intent)

        item_row = items.iloc[i_idx]
        generated_rows.append([u_id, item_row['item_id'], item_row['item_type'],
                               actions_map[act_idx], weights_map[act_idx]])

    # ============================================
    # BƯỚC 3: TẠO DATAFRAME VÀ LƯU
    # ============================================
    df_gen = pd.DataFrame(generated_rows, columns=['user_id', 'item_id', 'item_type', 'action_type', 'action_weight'])

    # Trộn ngẫu nhiên thứ tự dòng để giống dữ liệu thật
    df_gen = df_gen.sample(frac=1).reset_index(drop=True)

    # Thêm ID tự tăng
    df_gen.insert(0, 'interaction_id', range(1, 1 + len(df_gen)))

    # Lưu file
    df_gen.to_csv(output_path, index=False)

    print(f"✅ Đã tạo xong {len(df_gen)} dòng tương tác.")
    print(f"📁 File saved at: {output_path}")
    print("\n📋 Xem trước dữ liệu:")
    print(df_gen.head(10))

    # Check nhanh logic
    print("\n🔍 Kiểm tra Logic:")
    sample_user = df_gen['user_id'].iloc[0]
    user_interactions = df_gen[df_gen['user_id'] == sample_user]
    print(f"User {sample_user} đã tương tác với các item có type: {user_interactions['item_type'].unique()}")
    # Nếu code đúng, 1 user sẽ chỉ có 1 loại sở thích (ví dụ chỉ toàn 'tour' hoặc chỉ toàn item rẻ)

else:
    print("❌ Không tìm thấy file input ai_item_tower_export... Hãy kiểm tra lại đường dẫn.")

# ======================================================
# PHẦN 1: SINH DỮ LIỆU TƯƠNG TÁC (DATA GENERATION) - IMPROVED VERSION
# ======================================================
import pandas as pd
import numpy as np
import os
from google.colab import drive

# 1. Kết nối Drive & Cấu hình đường dẫn
drive.mount('/content/drive')
BASE_PATH = '/content/drive/MyDrive/tripfinity/data'
ITEMS_PATH = f'{BASE_PATH}/ai_item_tower_export_20251217_181044.csv'
OUTPUT_PATH = f'{BASE_PATH}/generated_user_item_interactions_50k_final.csv'

print("🔄 Đang tải dữ liệu Item gốc...")
try:
    items = pd.read_csv(ITEMS_PATH)
except FileNotFoundError:
    print("⚠️ Không tìm thấy file trên Drive, thử tìm file local...")
    items = pd.read_csv('ai_item_tower_export_20251217_181044.csv')
    OUTPUT_PATH = 'generated_user_item_interactions_50k_final.csv'

# 2. Xử lý sơ bộ Item
items['unique_item_id'] = items['item_type'] + "_" + items['item_id'].astype(str)
items['price'] = pd.to_numeric(items['price'], errors='coerce').fillna(items['price'].median())

# 3. Phân loại Item vào các nhóm
cheap_items = items[items['price'] < 500000].index.tolist()
luxury_items = items[(items['price'] >= 1000000) & (items['item_type'] == 'hotel')].index.tolist()
# Fallback nếu ít item luxury quá
if len(luxury_items) < 10:
    luxury_items = items[items['price'] >= 500000].index.tolist()
tour_items = items[items['item_type'] == 'tour'].index.tolist()

# Lấy danh sách tất cả index để dùng cho Warm-up và Random
all_items_indices = items.index.tolist()

print(f"📊 Stats: Cheap: {len(cheap_items)} | Luxury: {len(luxury_items)} | Tour: {len(tour_items)}")
print(f"📦 Total Items: {len(all_items_indices)}")

# ======================================================
# 4. Thiết lập User & Quy luật (ID 3 -> 2000)
# ======================================================
# np.arange(start, stop) -> lấy từ start đến stop-1.
# Muốn lấy đến 2000 thì phải điền 2001.
user_ids = np.arange(3, 2001)
n_users = len(user_ids)

print(f"👥 User ID range: {user_ids.min()} -> {user_ids.max()} (Total: {n_users} users)")

np.random.shuffle(user_ids)

# Chia user thành 3 nhóm sở thích
split = n_users // 3
user_groups = {}

# Nhóm 1: Budget
for u in user_ids[:split]: user_groups[u] = 'budget'
# Nhóm 2: Luxury
for u in user_ids[split:split*2]: user_groups[u] = 'luxury'
# Nhóm 3: Tour
for u in user_ids[split*2:]: user_groups[u] = 'tour'

# ======================================================
# 5. Sinh 50.000 dòng tương tác (Logic Nâng Cao)
# ======================================================
print("⚡ Đang sinh 50,000 dòng dữ liệu...")
generated_rows = []
actions = ['view', 'click', 'book', 'favorite']
weights = [2, 3, 5, 4]
prob_actions = [0.3, 0.3, 0.2, 0.2] # Tỷ lệ hành động

# --- GIAI ĐOẠN 1: WARM-UP (Đảm bảo phủ kín Item) ---
# Duyệt qua TẤT CẢ item, mỗi item gán cho 1 user ngẫu nhiên hành động 'view'
print("   -> Giai đoạn 1: Warm-up (Đảm bảo item nào cũng có tương tác)...")
for idx in all_items_indices:
    u_id = np.random.choice(user_ids)
    item_row = items.iloc[idx]

    # Mặc định warm-up là view (nhẹ nhất)
    generated_rows.append([
        u_id, item_row['item_id'], item_row['item_type'],
        'view', 2, item_row['unique_item_id']
    ])

# --- GIAI ĐOẠN 2: FILL DATA (Sinh số lượng còn lại) ---
remaining_count = 50000 - len(generated_rows)
print(f"   -> Giai đoạn 2: Sinh tiếp {remaining_count} dòng theo quy luật & khám phá...")

for _ in range(remaining_count):
    u_id = np.random.choice(user_ids)
    group = user_groups[u_id]

    # LOGIC KHÁM PHÁ (Exploration):
    # 10% cơ hội user sẽ click vào item bất kỳ (không theo nhóm sở thích)
    # Điều này giúp mô hình học được các item "lọt khe" (giá tầm trung)
    is_explore = np.random.random() < 0.10

    if is_explore:
        i_idx = np.random.choice(all_items_indices)
    else:
        # 90% Tuân thủ sở thích nhóm
        if group == 'budget':
            # Nếu list rỗng thì fallback về random toàn bộ
            i_idx = np.random.choice(cheap_items) if cheap_items else np.random.choice(all_items_indices)
        elif group == 'luxury':
            i_idx = np.random.choice(luxury_items) if luxury_items else np.random.choice(all_items_indices)
        else: # tour
            i_idx = np.random.choice(tour_items) if tour_items else np.random.choice(all_items_indices)

    item_row = items.iloc[i_idx]

    # Chọn hành động
    idx_act = np.random.choice(len(actions), p=prob_actions)

    generated_rows.append([
        u_id, item_row['item_id'], item_row['item_type'],
        actions[idx_act], weights[idx_act], item_row['unique_item_id']
    ])

# 6. Lưu file & Kiểm tra
interactions = pd.DataFrame(generated_rows, columns=['user_id', 'item_id', 'item_type', 'action_type', 'action_weight', 'unique_item_id'])
interactions.insert(0, 'interaction_id', range(1, 1 + len(interactions)))

# Check độ phủ Item
covered_items = interactions['unique_item_id'].nunique()
total_items = len(all_items_indices)

print("-" * 40)
print(f"✅ ĐÃ SINH XONG! File lưu tại: {OUTPUT_PATH}")
print(f"📋 Check User ID Min: {interactions['user_id'].min()}")
print(f"📋 Check User ID Max: {interactions['user_id'].max()}")
print(f"🎯 Độ phủ Item: {covered_items}/{total_items} ({(covered_items/total_items)*100:.2f}%)")
print("-" * 40)

interactions.to_csv(OUTPUT_PATH, index=False)
print(interactions.head())