/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        light: {
          primary: "#34A853",
          primaryHover: "#2C8B47",
          secondary: "#D9F2E7",
          background: "#FFFFFF",
          card: "#F8F9FA",
          textPrimary: "#212121",
          textSecondary: "#616161",
          textDisabled: "#9E9E9E",
          border: "#E0E0E0",
          icon: "#34A853",
          iconDisabled: "#BDBDBD",
          buttonText: "#FFFFFF",
          buttonDisabledBg: "#E0E0E0",
          buttonDisabledText: "#9E9E9E",
          warning: "#FFA726",
          error: "#E53935",
          errorBg: "#FFEBEE",
          success: "#43A047",
          info: "#29B6F6",
          focus: "#34A853",
          overlay: "#00000066",
          skeleton: "#EEEEEE",
          divider: "#F0F0F0",
        },
        dark: {
          primary: "#34A853",
          primaryHover: "#2C8B47",
          secondary: "#1E3D34",
          background: "#121212",
          card: "#1E1E1E",
          textPrimary: "#FFFFFF",
          textSecondary: "#BDBDBD",
          textDisabled: "#757575",
          border: "#333333",
          icon: "#34A853",
          iconDisabled: "#666666",
          buttonText: "#FFFFFF",
          buttonDisabledBg: "#333333",
          buttonDisabledText: "#757575",
          warning: "#FFB74D",
          error: "#EF5350",
          errorBg: "#311111",
          success: "#66BB6A",
          info: "#4FC3F7",
          focus: "#34A853",
          overlay: "#00000066",
          skeleton: "#2C2C2C",
          divider: "#2A2A2A",
        },
      },
      fontSize: {
        // Desktop
        "display-hero-desktop": [
          "56px",
          { lineHeight: "-0.5px", fontWeight: "700" },
        ],
        "h1-desktop": ["40px", { lineHeight: "-0.5px", fontWeight: "700" }],
        "h2-desktop": ["32px", { lineHeight: "-0.25px", fontWeight: "600" }],
        "h3-desktop": ["28px", { lineHeight: "auto", fontWeight: "600" }],
        "h4-desktop": ["24px", { lineHeight: "auto", fontWeight: "600" }],
        "h5-desktop": ["20px", { lineHeight: "auto", fontWeight: "600" }],
        "subtitle1-desktop": [
          "18px",
          { lineHeight: "auto", fontWeight: "500" },
        ],
        "subtitle2-desktop": [
          "16px",
          { lineHeight: "auto", fontWeight: "500" },
        ],
        "body1-desktop": ["16px", { lineHeight: "auto", fontWeight: "400" }],
        "body2-desktop": ["14px", { lineHeight: "auto", fontWeight: "400" }],
        "caption-desktop": ["12px", { lineHeight: "auto", fontWeight: "400" }],
        "button-desktop": ["16px", { lineHeight: "auto", fontWeight: "600" }],
        "overline-desktop": ["12px", { lineHeight: "auto", fontWeight: "500" }],
        // Tablet

        "display-hero-tablet": [
          "40px",
          { lineHeight: "-0.5px", fontWeight: "700" },
        ],
        "h1-tablet": ["32px", { lineHeight: "-0.5px", fontWeight: "700" }],
        "h2-tablet": ["28px", { lineHeight: "-0.25px", fontWeight: "600" }],
        "h3-tablet": ["24px", { lineHeight: "auto", fontWeight: "600" }],
        "h4-tablet": ["20px", { lineHeight: "auto", fontWeight: "600" }],
        "h5-tablet": ["18px", { lineHeight: "auto", fontWeight: "600" }],
        "subtitle1-tablet": ["16px", { lineHeight: "auto", fontWeight: "500" }],
        "subtitle2-tablet": ["14px", { lineHeight: "auto", fontWeight: "500" }],
        "body1-tablet": ["14px", { lineHeight: "auto", fontWeight: "400" }],
        "body2-tablet": ["12px", { lineHeight: "auto", fontWeight: "400" }],
        "caption-tablet": ["12px", { lineHeight: "auto", fontWeight: "400" }],
        "button-tablet": ["14px", { lineHeight: "auto", fontWeight: "600" }],
        "overline-tablet": ["12px", { lineHeight: "auto", fontWeight: "500" }],

        // Mobile
        "display-hero-mobile": [
          "32px",
          { lineHeight: "-0.5px", fontWeight: "700" },
        ],
        "h1-mobile": ["28px", { lineHeight: "-0.5px", fontWeight: "700" }],
        "h2-mobile": ["24px", { lineHeight: "-0.25px", fontWeight: "600" }],
        "h3-mobile": ["20px", { lineHeight: "auto", fontWeight: "600" }],
        "h4-mobile": ["18px", { lineHeight: "auto", fontWeight: "600" }],
        "h5-mobile": ["16px", { lineHeight: "auto", fontWeight: "600" }],
        "subtitle1-mobile": ["16px", { lineHeight: "auto", fontWeight: "500" }],
        "subtitle2-mobile": ["14px", { lineHeight: "auto", fontWeight: "500" }],
        "body1-mobile": ["14px", { lineHeight: "auto", fontWeight: "400" }],
        "body2-mobile": ["12px", { lineHeight: "auto", fontWeight: "400" }],
        "caption-mobile": ["12px", { lineHeight: "auto", fontWeight: "400" }],
        "button-mobile": ["14px", { lineHeight: "auto", fontWeight: "600" }],
        "overline-mobile": ["12px", { lineHeight: "auto", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
